// Code generated by protoc-gen-go.
// source: user/user.proto
// DO NOT EDIT!

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user/user.proto

It has these top-level messages:
	User
	RegisterRequest
	RegisterResponse
	LoginRequest
	LoginResponse
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import kudu_type "github.com/synoday/golang/protogen/type/creds"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ResponseStatus is response status enum.
type ResponseStatus int32

const (
	ResponseStatus_UNKNOWN                     ResponseStatus = 0
	ResponseStatus_SUCCESS                     ResponseStatus = 1
	ResponseStatus_INTERNAL_ERROR              ResponseStatus = 2
	ResponseStatus_CREDENTIAL_INVALID          ResponseStatus = 16
	ResponseStatus_CREDENTIAL_INVALID_EMAIL    ResponseStatus = 17
	ResponseStatus_CREDENTIAL_INVALID_USERNAME ResponseStatus = 18
	ResponseStatus_CREDENTIAL_INVALID_PASSWORD ResponseStatus = 19
	ResponseStatus_CREDENTIAL_NOT_VERIFIED     ResponseStatus = 20
	ResponseStatus_USER_INVALID_FIRST_NAME     ResponseStatus = 32
)

var ResponseStatus_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "SUCCESS",
	2:  "INTERNAL_ERROR",
	16: "CREDENTIAL_INVALID",
	17: "CREDENTIAL_INVALID_EMAIL",
	18: "CREDENTIAL_INVALID_USERNAME",
	19: "CREDENTIAL_INVALID_PASSWORD",
	20: "CREDENTIAL_NOT_VERIFIED",
	32: "USER_INVALID_FIRST_NAME",
}
var ResponseStatus_value = map[string]int32{
	"UNKNOWN":                     0,
	"SUCCESS":                     1,
	"INTERNAL_ERROR":              2,
	"CREDENTIAL_INVALID":          16,
	"CREDENTIAL_INVALID_EMAIL":    17,
	"CREDENTIAL_INVALID_USERNAME": 18,
	"CREDENTIAL_INVALID_PASSWORD": 19,
	"CREDENTIAL_NOT_VERIFIED":     20,
	"USER_INVALID_FIRST_NAME":     32,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}
func (ResponseStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// User hold user information.
type User struct {
	// id is user unique identifier.
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// first_name is user first name.
	FirstName string `protobuf:"bytes,4,opt,name=first_name,json=firstName" json:"first_name,omitempty"`
	// last_name is user last name.
	LastName string `protobuf:"bytes,5,opt,name=last_name,json=lastName" json:"last_name,omitempty"`
	// created is user registration timestamp
	Created *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=created" json:"created,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetCreated() *google_protobuf.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

// RegisterRequest holds user registration information.
type RegisterRequest struct {
	// credential is user credential.
	Credential *kudu_type.Credential `protobuf:"bytes,1,opt,name=credential" json:"credential,omitempty"`
	// user is user profile information.
	User *User `protobuf:"bytes,2,opt,name=user" json:"user,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RegisterRequest) GetCredential() *kudu_type.Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

func (m *RegisterRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

// RegisterResponse holds the response of user registration.
type RegisterResponse struct {
	// status is the registration response status.
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,enum=kudu.item.ResponseStatus" json:"status,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RegisterResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

// LoginRequest holds login request information.
type LoginRequest struct {
	// credential is user claimed credential.
	Credential *kudu_type.Credential `protobuf:"bytes,1,opt,name=credential" json:"credential,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LoginRequest) GetCredential() *kudu_type.Credential {
	if m != nil {
		return m.Credential
	}
	return nil
}

// LoginResponse holds login request information.
type LoginResponse struct {
	// status is the login response status.
	Status ResponseStatus `protobuf:"varint,1,opt,name=status,enum=kudu.item.ResponseStatus" json:"status,omitempty"`
	// token is valid jwt token;
	Token string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LoginResponse) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_UNKNOWN
}

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "kudu.item.User")
	proto.RegisterType((*RegisterRequest)(nil), "kudu.item.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "kudu.item.RegisterResponse")
	proto.RegisterType((*LoginRequest)(nil), "kudu.item.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "kudu.item.LoginResponse")
	proto.RegisterEnum("kudu.item.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/kudu.item.UserService/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := grpc.Invoke(ctx, "/kudu.item.UserService/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kudu.item.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kudu.item.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 533 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x93, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0xeb, 0xa8, 0x49, 0x9b, 0x09, 0x24, 0xcb, 0x52, 0xa8, 0x71, 0x40, 0x8d, 0xcc, 0x81,
	0xc2, 0xc1, 0x16, 0x01, 0x6e, 0x5c, 0x42, 0xb2, 0x95, 0x2c, 0x52, 0x07, 0xad, 0x93, 0x16, 0x71,
	0xb1, 0x9c, 0x78, 0x6b, 0xac, 0xc6, 0x76, 0xf0, 0xae, 0x91, 0xf2, 0x06, 0x9c, 0x79, 0x52, 0x1e,
	0x01, 0xed, 0xba, 0x0e, 0x89, 0x5a, 0x2e, 0x70, 0xb1, 0xb4, 0xf3, 0xfd, 0x33, 0xfb, 0xcf, 0x8c,
	0x17, 0x3a, 0x05, 0x67, 0xb9, 0x2d, 0x3f, 0xd6, 0x2a, 0xcf, 0x44, 0x86, 0x9b, 0xd7, 0x45, 0x58,
	0x58, 0xb1, 0x60, 0x89, 0x71, 0x12, 0x65, 0x59, 0xb4, 0x64, 0xb6, 0x02, 0xf3, 0xe2, 0xca, 0x16,
	0x71, 0xc2, 0xb8, 0x08, 0x92, 0x55, 0xa9, 0x35, 0x90, 0x58, 0xaf, 0x98, 0xbd, 0xc8, 0x59, 0xc8,
	0xcb, 0x88, 0xf9, 0x43, 0x83, 0xfd, 0x19, 0x67, 0x39, 0x6e, 0x43, 0x2d, 0x0e, 0x75, 0xad, 0xa7,
	0x9d, 0x36, 0x69, 0x2d, 0x0e, 0xf1, 0x33, 0x80, 0xab, 0x38, 0xe7, 0xc2, 0x4f, 0x83, 0x84, 0xe9,
	0xfb, 0x2a, 0xde, 0x54, 0x11, 0x37, 0x48, 0x18, 0xee, 0x42, 0x73, 0x19, 0x54, 0xb4, 0xae, 0xe8,
	0xa1, 0x0c, 0x28, 0xf8, 0x16, 0x0e, 0x16, 0x39, 0x0b, 0x04, 0x0b, 0xf5, 0x46, 0x4f, 0x3b, 0x6d,
	0xf5, 0x0d, 0xab, 0x74, 0x66, 0x55, 0xce, 0xac, 0x69, 0xe5, 0x8c, 0x56, 0x52, 0x33, 0x81, 0x0e,
	0x65, 0x51, 0xcc, 0x05, 0xcb, 0x29, 0xfb, 0x56, 0x30, 0x2e, 0xf0, 0x3b, 0x00, 0x69, 0x96, 0xa5,
	0x22, 0x0e, 0x96, 0xca, 0x5c, 0xab, 0xff, 0xc8, 0x52, 0x0d, 0xcb, 0x4e, 0xac, 0xe1, 0x06, 0xd2,
	0x2d, 0x21, 0x7e, 0x0e, 0xfb, 0x72, 0x40, 0x7a, 0x4d, 0x25, 0x74, 0xac, 0xcd, 0x84, 0x2c, 0xd9,
	0x2a, 0x55, 0xd0, 0x24, 0x80, 0xfe, 0x5c, 0xc7, 0x57, 0x59, 0xca, 0x19, 0x7e, 0x0d, 0x0d, 0x2e,
	0x02, 0x51, 0x70, 0x75, 0x57, 0xbb, 0xff, 0x64, 0x2b, 0xb5, 0x12, 0x79, 0x4a, 0x40, 0x6f, 0x84,
	0x26, 0x81, 0x7b, 0xe3, 0x2c, 0x8a, 0xd3, 0xff, 0xb3, 0x6c, 0x7e, 0x86, 0xfb, 0x37, 0x65, 0xfe,
	0xd9, 0x0a, 0x3e, 0x82, 0xba, 0xc8, 0xae, 0x59, 0xaa, 0xfa, 0x6e, 0xd2, 0xf2, 0xf0, 0xea, 0x97,
	0x06, 0xed, 0xdd, 0x04, 0xdc, 0x82, 0x83, 0x99, 0xfb, 0xd1, 0x9d, 0x5c, 0xba, 0x68, 0x4f, 0x1e,
	0xbc, 0xd9, 0x70, 0x48, 0x3c, 0x0f, 0x69, 0x18, 0x43, 0xdb, 0x71, 0xa7, 0x84, 0xba, 0x83, 0xb1,
	0x4f, 0x28, 0x9d, 0x50, 0x54, 0xc3, 0x8f, 0x01, 0x0f, 0x29, 0x19, 0x11, 0x77, 0xea, 0x0c, 0xc6,
	0xbe, 0xe3, 0x5e, 0x0c, 0xc6, 0xce, 0x08, 0x21, 0xfc, 0x14, 0xf4, 0xdb, 0x71, 0x9f, 0x9c, 0x0f,
	0x9c, 0x31, 0x7a, 0x80, 0x4f, 0xa0, 0x7b, 0x07, 0x9d, 0x79, 0xb2, 0xf6, 0x39, 0x41, 0xf8, 0x2f,
	0x82, 0x4f, 0x03, 0xcf, 0xbb, 0x9c, 0xd0, 0x11, 0x7a, 0x88, 0xbb, 0x70, 0xbc, 0x25, 0x70, 0x27,
	0x53, 0xff, 0x82, 0x50, 0xe7, 0xcc, 0x21, 0x23, 0x74, 0x24, 0xa1, 0xac, 0xb5, 0xc9, 0x3b, 0x73,
	0xa8, 0x37, 0xf5, 0x55, 0xe9, 0x5e, 0xff, 0xa7, 0x06, 0x2d, 0xb9, 0x69, 0x8f, 0xe5, 0xdf, 0xe3,
	0x05, 0xc3, 0x04, 0x0e, 0xab, 0x55, 0x63, 0x63, 0x67, 0x8e, 0x3b, 0xbf, 0x9b, 0xd1, 0xbd, 0x93,
	0x95, 0xa3, 0x33, 0xf7, 0xf0, 0x7b, 0xa8, 0xab, 0x1d, 0xe1, 0xe3, 0x2d, 0xdd, 0xf6, 0xf2, 0x0d,
	0xfd, 0x36, 0xa8, 0xb2, 0x3f, 0xbc, 0xfc, 0xf2, 0x22, 0x8a, 0xc5, 0xd7, 0x62, 0x6e, 0x2d, 0xb2,
	0xc4, 0xe6, 0xeb, 0x34, 0x0b, 0x83, 0xb5, 0x1d, 0x65, 0xcb, 0x20, 0x8d, 0xca, 0x17, 0x1b, 0xb1,
	0x54, 0x3d, 0xec, 0x79, 0x43, 0x1d, 0xdf, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x71, 0xcd, 0xe4,
	0xb6, 0xec, 0x03, 0x00, 0x00,
}
